{
 "title": "Google Cloud Billing Costs",
 "time": { "from": "2020-06-01T00:00:00.000Z", "to": "2020-06-30T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "SELECT DISTINCT project.id FROM `$table_billing`"
   },
   { "name": "dataset", "label": "Billing Dataset", "query": "${VAR_DATASET}" },
   {
    "name": "table_billing",
    "label": "Billing Table",
    "query": "SELECT CONCAT(table_catalog, \".\", table_schema, \".\", table_name) FROM `$dataset.INFORMATION_SCHEMA.TABLES` WHERE REGEXP_CONTAINS(table_name, \"^gcp_billing_export_v1_\")"
   }
  ]
 },
 "panels": [
  { "title": "Billing Account Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Yesterday's Spend by Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Cost ($)" }
   ],
   "targets": [
    {
     "dataset": "billing",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT\n  service.description AS metric,\n  SUM(cost) AS value,\n  CURRENT_TIMESTAMP() AS time_sec\nFROM\n  `$table_billing`\nWHERE\n  DATE(usage_start_time) = DATE_SUB(DATE(CURRENT_TIMESTAMP()), INTERVAL 1 DAY)\nGROUP BY 1\nORDER BY 2 DESC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Month-to-date Spend by Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Cost ($)" }
   ],
   "targets": [
    {
     "dataset": "billing",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT\n  service.description AS metric,\n  SUM(cost) AS value,\n  CURRENT_TIMESTAMP() AS time_sec\nFROM\n  `$table_billing`\nWHERE\n  DATE_TRUNC(DATE(usage_start_time), MONTH) = DATE_TRUNC(DATE(CURRENT_TIMESTAMP()), MONTH)\nGROUP BY 1\nORDER BY 2 DESC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Month-to-date Spend by Project",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Cost ($)" }
   ],
   "targets": [
    {
     "dataset": "billing",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT\n  project.id AS metric,\n  SUM(cost) AS value,\n  CURRENT_TIMESTAMP() AS time_sec\nFROM\n  `$table_billing`\nWHERE\n  DATE_TRUNC(DATE(usage_start_time), MONTH) = DATE_TRUNC(DATE(CURRENT_TIMESTAMP()), MONTH)\nGROUP BY 1\nORDER BY 2 DESC"
    }
   ]
  },
  {
   "title": "Daily Spend by Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "Cost ($)" }
   ],
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT\n  TIMESTAMP(date) AS time_sec,\n  IFNULL(service.description, '_') AS metric,\n  SUM(cost)\nFROM \n  (\n    SELECT date FROM UNNEST(\n      GENERATE_DATE_ARRAY(\n        DATE_TRUNC(CURRENT_DATE(), MONTH),\n        DATE(EXTRACT(YEAR FROM CURRENT_DATE()), EXTRACT(MONTH FROM CURRENT_DATE()), 32 - EXTRACT(DAY FROM DATE_ADD(DATE_TRUNC(CURRENT_DATE(), MONTH), INTERVAL 31 DAY)))\n      )\n    ) AS date\n  )\n  LEFT JOIN `$table_billing` ON DATE(usage_start_time) = date\nGROUP BY 1, 2\nORDER BY 1, 2"
    }
   ]
  },
  {
   "title": "Monthly Spend Breakdown by Service",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT\n  service.description AS metric,\n  SUM(cost) AS value,\n  CURRENT_TIMESTAMP() AS time_sec\nFROM\n  `$table_billing`\nWHERE\n  invoice.month = FORMAT_DATE(\"%Y%m\", CURRENT_DATE())\nGROUP BY 1\nHAVING value > 0\nORDER BY 2 DESC"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT\n  SUM(cost) AS ytd,\n  CURRENT_TIMESTAMP() AS time_sec\nFROM\n  `$table_billing`\nWHERE\n  DATE(usage_start_time) >= DATE(EXTRACT(YEAR FROM CURRENT_DATE()), 1, 1) AND\n  DATE(usage_start_time) <= DATE(EXTRACT(YEAR FROM CURRENT_DATE()), 12, 31)"
    },
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "DECLARE Q DEFAULT EXTRACT(QUARTER FROM CURRENT_DATE());\nDECLARE Y DEFAULT EXTRACT(YEAR FROM CURRENT_DATE());\n\nSELECT\n  SUM(cost) AS qtd,\n  CURRENT_TIMESTAMP() AS time_sec\nFROM\n  `$table_billing`\nWHERE\n  DATE(usage_start_time) >= DATE(Y, (Q - 1) * 3 + 1, 1) AND\n  DATE(usage_start_time) <= DATE_SUB(DATE_ADD(DATE(Y, Q * 3, 1), INTERVAL 1 MONTH), INTERVAL 1 DAY)"
    },
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT\n  SUM(cost) AS mtd,\n  CURRENT_TIMESTAMP() AS time_sec\nFROM\n  `$table_billing`\nWHERE\n  invoice.month = FORMAT_DATE(\"%Y%m\", CURRENT_DATE())"
    }
   ]
  }
 ]
}